[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_donation = "EDuB9MCqPUAbjfTsrRak2v1V99G45z4nBV6vCcLjLx6v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/bhaskarkh/wallet/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
